FROM golang:1.18 as ndt-server-build
RUN apt-get update && apt-get install -y openssl bash

ADD . /go/src/github.com/m-lab/ndt-server
ADD ./html /html

RUN /go/src/github.com/m-lab/ndt-server/build.sh
RUN cp /go/bin/ndt-server /
RUN cp /go/src/github.com/m-lab/ndt-server/gen_local_test_certs.bash /

WORKDIR /
CMD ["/ndt-server"]
